### ISSUE TITLE
Neko with XFCE, shall we do a pull request ? 

### ISSUE THREAD

**Issue by efelem** [deepsquare-io/workflow-catalog#2]
I was able to push an image to deepsquare registry that has GPU support with XFCE 

The image was build from the neko repo 

```bash
git clone https://github.com/m1k1o/neko.git
cd .docker
./build nvidia-base
./build nvidia-xfce
``` 

The image pushed to `registry-1.deepsquare.run` is `library/neko:nvidia-xfce`

The associated workflow file is similar to the neko.yaml only the image changes. Not sure if its worth putting a new workflow file maybe updating the README.md suffice ? 

![Screenshot from 2023-11-25 09-21-53](https://github.com/deepsquare-io/workflow-catalog/assets/745864/ab022550-267c-466d-a3d6-5bb97ff5e6ca)

**Comment by Darkness4** [comment]
You can add a new workflow file.

**Comment by Darkness4** [comment]
By the way, xfce is not running on nvidia (you can see no running processes). To run on nvidia, you need to execute `vglrun <executable>` or the given entrypoint `/bin/entrypoint.sh <executable>`.

I'm rebuilding you image with nvidia.

**Comment by Darkness4** [comment]
It's working well, actually, let me do the workflow file.
![image](https://github.com/deepsquare-io/workflow-catalog/assets/18192844/46f9d3ad-8a5b-4544-9b9b-e55feafb0fc0)
